apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-cloudflared-egress
  namespace: cloudflared
spec:
  endpointSelector:
    matchLabels:
      app: cloudflared
  egress:
    - toEntities:
        - all
