# Create your tunnel at: https://one.dash.cloudflare.com/ -> Zero Trust -> Networks -> Tunnels
# Then create this secret with your tunnel token:
#   kubectl create secret generic cloudflared-tunnel -n cloudflared --from-literal=TUNNEL_TOKEN=<your-token>
#
# Or replace this file with a SealedSecret/SOPS encrypted version
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
type: Opaque
stringData:
  TUNNEL_TOKEN: "REPLACE_WITH_YOUR_TUNNEL_TOKEN"
