apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: keycloak-admin-credentials
    creationPolicy: Owner
    template:
      data:
        username: admin
  data:
    - secretKey: password
      remoteRef:
        key: keycloak-admin-password
