apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: keycloak-operator
  namespace: keycloak
spec:
  interval: 1h
  url: https://github.com/keycloak/keycloak-k8s-resources
  ref:
    tag: "26.0.7"
