apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: keycloak-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: keycloak
  data:
    - secretKey: password
      remoteRef:
        key: keycloak-db-password
