apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy-longhorn
  namespace: oauth2-proxy
spec:
  interval: 1h
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.x"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: oauth2-proxy
  values:
    replicaCount: 1

    config:
      existingSecret: oauth2-proxy-secrets
      cookieName: _oauth2_proxy

    extraArgs:
      provider: oidc
      oidc-issuer-url: https://auth.taya.net/realms/tayacluster
      skip-oidc-discovery: "true"
      login-url: https://auth.taya.net/realms/tayacluster/protocol/openid-connect/auth
      redeem-url: http://keycloak-service.keycloak.svc.cluster.local:8080/realms/tayacluster/protocol/openid-connect/token
      oidc-jwks-url: http://keycloak-service.keycloak.svc.cluster.local:8080/realms/tayacluster/protocol/openid-connect/certs
      email-domain: "*"
      cookie-secure: "true"
      cookie-samesite: lax
      set-xauthrequest: "true"
      set-authorization-header: "true"
      pass-authorization-header: "true"
      skip-provider-button: "true"
      upstream: http://longhorn-frontend.longhorn-system.svc.cluster.local:80
      http-address: 0.0.0.0:4180
      reverse-proxy: "true"
      whitelist-domain: .taya.net
      cookie-domain: .taya.net

    service:
      type: ClusterIP
      portNumber: 4180

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
