apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy-flux
  namespace: oauth2-proxy
spec:
  interval: 1h
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.x"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: oauth2-proxy
  values:
    replicaCount: 1

    config:
      clientID: oauth2-proxy
      cookieName: _oauth2_proxy_flux

    extraArgs:
      provider: oidc
      oidc-issuer-url: https://auth.taya.net/realms/tayacluster
      email-domain: "*"
      cookie-secure: "true"
      cookie-samesite: lax
      set-xauthrequest: "true"
      set-authorization-header: "true"
      pass-authorization-header: "true"
      skip-provider-button: "true"
      upstream: http://weave-gitops.weave-gitops.svc.cluster.local:9001
      http-address: 0.0.0.0:4180
      reverse-proxy: "true"
      whitelist-domain: .taya.net
      cookie-domain: .taya.net

    extraEnv:
      - name: OAUTH2_PROXY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-secrets
            key: client-secret
      - name: OAUTH2_PROXY_COOKIE_SECRET
        valueFrom:
          secretKeyRef:
            name: oauth2-proxy-secrets
            key: cookie-secret

    service:
      type: ClusterIP
      portNumber: 4180

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
