apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: grafana-admin-password
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      data:
        admin-user: admin
  data:
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
