apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1h
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      chart: loki
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    # Deploy as single binary (simplest for small cluster)
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      storage:
        type: filesystem
      limits_config:
        retention_period: 168h  # 7 days

    # Single binary configuration
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
      persistence:
        enabled: true
        size: 20Gi

    # Disable other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    # Disable gateway when using single binary
    gateway:
      enabled: false

    # Disable chunksCache, resultsCache for simplicity
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
