apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mediawiki
  namespace: mediawiki
spec:
  interval: 1h
  chart:
    spec:
      chart: mediawiki
      version: "1.10.x"
      sourceRef:
        kind: HelmRepository
        name: mediawiki
        namespace: mediawiki
  values:
   