apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "1.8.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
              name: longhorn-manager
            patch: |
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: longhorn-hdd
                  hostPath:
                    path: /var/lib/longhorn-hdd
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: longhorn-hdd
                  mountPath: /var/lib/longhorn-hdd
                  mountPropagation: Bidirectional
  values:
    defaultSettings:
      defaultDataPath: /var/lib/longhorn
      defaultReplicaCount: 2
      replicaSoftAntiAffinity: true
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 15
      createDefaultDiskLabeledNodes: true

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2

    ingress:
      enabled: false

    longhornUI:
      replicas: 1
