apiVersion: v1
kind: Service
metadata:
  name: cilium-ingress-internal
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cilium-ingress-internal
spec:
  type: ClusterIP
  selector:
    k8s-app: cilium-envoy
  ports:
    - name: http
      port: 80
      targetPort: 9080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP
