apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.16.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  values:
    # Talos-specific settings
    ipam:
      mode: kubernetes

    # Use native routing instead of VXLAN tunnel for flat L2 network
    routingMode: native
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    autoDirectNodeRoutes: true

    # Kube-proxy replacement
    kubeProxyReplacement: true
    k8sServiceHost: localhost
    k8sServicePort: 7445  # KubePrism port from Talos config

    # BPF masquerading for egress
    bpf:
      masquerade: true

    # Security
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    # Ingress Controller
    ingressController:
      enabled: true
      default: true
      loadbalancerMode: dedicated
      service:
        type: NodePort
