apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mediawiki-credentials
  namespace: mediawiki
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: mediawiki-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: mediawiki-admin-user
    - secretKey: admin-password
      remoteRef:
        key: mediawiki-admin-password
    - secretKey: db-user
      remoteRef:
        key: mediawiki-db-user
    - secretKey: db-password
      remoteRef:
        key: mediawiki-db-password
